name: documentation
on:
  release:
    types:
      - published

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2
      
      # Set up Python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      # Install Poetry and dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with docs
      
      # Generate API documentation
      - name: Build documentation
        run: |
          poetry run sphinx-apidoc -o docs/source easy_http_requests
          rm -rf docs/_build   # Clean build directory
          poetry run sphinx-build -b html docs/source docs/_build
      
      # Deploy to GitHub Pages
      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build
          force_orphan: true
